services:
  argos_api_app_stage:
    image: argos-api-app-stage
    build:
      context: ..
      dockerfile: Dockerfile.stage
    ports:
      - "8082:8082"
    depends_on:
      - argos_api_postgres_stage
    profiles:
      - stage

  argos_api_postgres_stage:
    container_name: argos_api_postgres_stage_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${STAGE_DB_NAME}
      POSTGRES_USER: ${STAGE_DB_USERNAME}
      POSTGRES_PASSWORD: ${STAGE_DB_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - postgres_stage_data:/var/lib/postgresql/data
    profiles:
      - stage
    env_file:
      - .env

volumes:
  postgres_stage_data: {}
