FROM gradle:8.10.2-jdk17-alpine AS build

WORKDIR /app

COPY . .

RUN ./gradlew --no-daemon build -x test

FROM eclipse-temurin:17-alpine AS runtime

WORKDIR /app

COPY --from=build /app/build/libs/argos-api-0.0.1-SNAPSHOT.jar ./

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "/app/argos-api-0.0.1-SNAPSHOT.jar"]
