services:
  argos_api_app_dev:
    image: argos-api-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    depends_on:
      - argos_api_postgres_dev
    profiles:
      - development

  argos_api_postgres_dev:
    container_name: argos_api_postgres_dev
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres_development_data:/var/lib/postgresql/data
    profiles:
      - development
    env_file:
      - .env

volumes:
  postgres_development_data: {}
