services:
  argos_prod:
    image: argos-prod-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      SPRING_DATASOURCE_URL: ${PROD_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PROD_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROD_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8282:8282"
    depends_on:
      - postgres_prod
    profiles:
      - production
    env_file:
      - .env

  postgres_prod:
    container_name: postgres_prod_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PROD_PSQL_DB_URL}
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
    profiles:
      - production

volumes:
  postgres_production_data: {}
