services:
  argos_api_app_prod:
    image: argos-api-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8282:8282"
    depends_on:
      - argos_api_postgres_prod
    profiles:
      - production

  argos_api_postgres_prod:
    container_name: argos_api_postgres_prod
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PROD_DB_NAME}
      POSTGRES_USER: ${PROD_DB_USERNAME}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
    profiles:
      - production
    env_file:
      - .env

volumes:
  postgres_production_data: {}
