spring:
  application:
    name: argos-api
    
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  profiles:
    active: dev

file:
  manager:
    base-url: http://localhost:8081/fileManager
