spring.datasource.url=jdbc:postgresql://localhost:5432/apirestDB
spring.datasource.username=postgres
spring.datasource.password=admin

spring.flyway.enabled=false
logging.level.org.springframework=DEBUG
spring.jpa.hibernate.ddl-auto=none
