spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG