spring:
  application:
    name: argos-api

  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG
