package com.argos.apirest.types;

public enum IssueType {
    SYNTAX_ERROR,
    LOGIC_ERROR,
    PERFORMANCE_ISSUE,
    SECURITY_ISSUE,
    CODE_STYLE_VIOLATION,
    DUPLICATE_CODE,
    UNUSED_CODE,
    HARD_CODED_VALUES,
    DEPENDENCY_ISSUE,
    BEST_PRACTICE_VIOLATION,
    COMPLEXITY_ISSUE,
    THREAD_SAFETY_ISSUE,
    OBSOLETE_CODE
}
