name: Deployment

on:
  push:
    branches: production

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: argoscs
          IMAGE_NAME: argoscs/api
        run: |
          docker build -t ${IMAGE_NAME} -f Dockerfile.prod .

      - name: Push Docker Image
        run: |
          docker push ${IMAGE_NAME}

      - name: Deploy to Server
        run: echo "Deployment"
        