name: Sonarqube pipeline

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  static-analisis:
    name: build and sonarqube analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          cd apirest && ./gradlew build --no-daemon

      - name: Compile
        run: |
          cd apirest && ./gradlew compileJava --no-daemon

      - name: Generate coverage reports
        run: |
          cd apirest && ./gradlew jacocoTestReport --no-daemon

      - name: SonarQube Scan
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
            SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
        run: |
          cd apirest && ./gradlew sonar --no-daemon
